project_id = "ahqauomkgflopxgnlndd"

[functions.insurance-eligibility]
verify_jwt = true

[functions.get-billable-appointments]
verify_jwt = true

[functions.claim-submission]
verify_jwt = true

[functions.claim-response]
verify_jwt = true

[functions.era-retrieval]
verify_jwt = true

[functions.donate-go]
verify_jwt = false

[functions.givebutter-webhook]
verify_jwt = false

[functions.google-ads-givebutter-feed]
verify_jwt = false
